### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by gerases** [sobjornstad/tzk#9]
Hi, is there way to increase the font size for everything in TZK without using the browser’s zoom in functionality?

**Comment by sobjornstad** [comment]
Base TiddlyWiki has settings for this in the Control Panel under Appearance > Theme Tweaks.

**Comment by sobjornstad** [comment]
![image](https://github.com/sobjornstad/tzk/assets/2313414/b05eb49f-b2bf-4317-be81-0d3961f7a928)
![image](https://github.com/sobjornstad/tzk/assets/2313414/698164cd-14f6-4dd4-aab4-31b7dc6ed22e)

**Comment by gerases** [comment]
Nice, thank you!
